[package]
name = "goose-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
regex = { workspace = true }
rmcp = { workspace = true, features = ["server"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing.workspace = true
unicode-normalization = { version = "0.1.25", default-features = false, features = ["std"] }
utoipa = { workspace = true }
uuid.workspace = true
